### ISSUE TITLE
LaTeX documentation

### ISSUE THREAD

**Issue by PiotrFedak** [kibolApp/kibolApp#101]
The task is to create a LaTeX documentation, i guess something similar to previous Pipsi 1 documentation. 

1. Skład oraz Opis ról w zespole 
2. Opis funkcjonaly systemu 
3. Wyszczególnione wdrożone kwalifikacje
4. Opis techniczny (streszczony)
5. Instrukcja uruchomienia
6. Link do repozytorium oraz strony ( gdy już uda się hostować)
7. Wnioski Projektowe

For reference old LaTeX doc
[Sprawozdanie.pdf](https://github.com/kibolApp/kibolApp/files/13908522/Sprawozdanie.pdf)

**Comment by KacperWojdak** [comment]
[Sprawozdanie projektowe.pdf](https://github.com/kibolApp/kibolApp/files/13933111/Sprawozdanie.projektowe.pdf)
