### ISSUE TITLE
Map Upgrade

### ISSUE THREAD

**Issue by KacperWojdak** [kibolApp/kibolApp#35]
After creating a map with club locations, the upgrade focuses on additional features:
- improving the zoom of the map so it doesn't disappear when it's too close,
- correct scaling of icons on the map
- links leading to the club description page in the window (other issue)

**Comment by PiotrFedak** [comment]
![08f76f7b4463c329af4cf5146f4eaa59](https://github.com/kibolApp/kibolApp/assets/115737114/61b01ee9-60db-4688-ae73-01af54a363a9)
![b5564494517cefaf7918a29905dd2f07](https://github.com/kibolApp/kibolApp/assets/115737114/74c0d1ae-26de-481b-aaa4-046344edf091)
Okay, the first thing I added is that when multiple clubs are on the same level so to speak, they now accumulate and then it gives the number of clubs in the area

**Comment by PiotrFedak** [comment]
https://github.com/kibolApp/kibolApp/assets/115737114/39fc5494-fc6f-4e00-91ab-e870894adfa7

For now under right mouse button is zooming in to closest football club.
